# Generated by Django 5.2.7 on 2025-11-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_eventlist_quiz_alter_uservideo_user_logdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='id',
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='event_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('quiz_difficulty', 'quiz_number')},
        ),
    ]
