# Generated by Django 5.2.7 on 2025-11-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_eventlist_id_remove_lesson_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdata',
            name='event',
        ),
        migrations.RemoveField(
            model_name='logdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventList',
        ),
        migrations.DeleteModel(
            name='LogData',
        ),
        migrations.DeleteModel(
            name='UserVideo',
        ),
    ]
